//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAGGLE.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.AccountAccountType = new HashSet<AccountAccountType>();
            this.AccountCategory = new HashSet<AccountCategory>();
            this.AccountCompany = new HashSet<AccountCompany>();
            this.AccountContact = new HashSet<AccountContact>();
            this.ProductAccountPrice = new HashSet<ProductAccountPrice>();
        }
    
        public int AccountId { get; set; }
        public string BusinessName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string Email { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public string City { get; set; }
        public string Description { get; set; }
        public string WebSite { get; set; }
        public string MobileNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<AccountAccountType> AccountAccountType { get; set; }
        public virtual ICollection<AccountCategory> AccountCategory { get; set; }
        public virtual ICollection<AccountCompany> AccountCompany { get; set; }
        public virtual ICollection<AccountContact> AccountContact { get; set; }
        public virtual ICollection<ProductAccountPrice> ProductAccountPrice { get; set; }
    }
}
