//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAGGLE.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        public Attribute()
        {
            this.AttributeCategory = new HashSet<AttributeCategory>();
            this.ProductAttribute = new HashSet<ProductAttribute>();
        }
    
        public int AttributeId { get; set; }
        public string FeatureName { get; set; }
        public int FeatureTypeId { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public bool Status { get; set; }
    
        public virtual FeatureType FeatureType { get; set; }
        public virtual ICollection<AttributeCategory> AttributeCategory { get; set; }
        public virtual ICollection<ProductAttribute> ProductAttribute { get; set; }
    }
}
