//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAGGLE.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.AccountCategory = new HashSet<AccountCategory>();
            this.AttributeCategory = new HashSet<AttributeCategory>();
            this.ProductCategory = new HashSet<ProductCategory>();
        }
    
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool IsSelectable { get; set; }
    
        public virtual ICollection<AccountCategory> AccountCategory { get; set; }
        public virtual ICollection<AttributeCategory> AttributeCategory { get; set; }
        public virtual ICollection<ProductCategory> ProductCategory { get; set; }
    }
}
