//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAGGLE.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDivision
    {
        public int ProductDivisionId { get; set; }
        public int ProductId { get; set; }
        public int DivisionId { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual Product Product { get; set; }
    }
}
