//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAGGLE.DAL.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductAccountPrice = new HashSet<ProductAccountPrice>();
            this.ProductAttribute = new HashSet<ProductAttribute>();
            this.ProductAvailability = new HashSet<ProductAvailability>();
            this.ProductPricing = new HashSet<ProductPricing>();
            this.ProductCategory = new HashSet<ProductCategory>();
            this.ProductDivision = new HashSet<ProductDivision>();
        }
    
        public int ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductTag { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Unit { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProductClassId { get; set; }
        public int StockType { get; set; }
        public bool IsPublic { get; set; }
        public bool Status { get; set; }
        public bool IsDefined { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual ProductClass ProductClass { get; set; }
        public virtual ICollection<ProductAccountPrice> ProductAccountPrice { get; set; }
        public virtual ICollection<ProductAttribute> ProductAttribute { get; set; }
        public virtual ICollection<ProductAvailability> ProductAvailability { get; set; }
        public virtual ICollection<ProductPricing> ProductPricing { get; set; }
        public virtual ICollection<ProductCategory> ProductCategory { get; set; }
        public virtual ICollection<ProductDivision> ProductDivision { get; set; }
    }
}
